"""
Deterministic orchestration of the bottom-up HLG-regeneration feedback loop.

The cycle starts from HLGs and LLGs already generated by the original top-down
pipeline. At each iteration it reconstructs one HLG' from each branch's current
LLGs and asks the Global Goal Evaluator for exactly one of two local decisions:

- CONFIRM_BRANCH: preserve the complete branch unchanged;
- REGENERATE_HIGH_LEVEL_GOAL: invoke the ORIGINAL HLG Generator -> HLG
  Evaluator loop to replace that branch's HLG, then ALWAYS invoke the ORIGINAL
  LLG Generator -> LLG Evaluator loop for the replacement before the next
  bottom-up iteration.

Only when every current branch is confirmed does global documentation coverage
run. Coverage receives the current HLG set and the confirmed reconstructed HLGs
as additional discovery signals. If documentation supports an autonomous
WHY-level intention not represented by any current HLG, coverage may request a
new HLG. Each added HLG is generated/evaluated, decomposed into evaluated LLGs,
and then re-enters the same bottom-up verification cycle.

``goal_update.py`` performs deterministic state mutation only. ``cycle_state.py``
performs convergence/repetition inspection only. There is one evolving current
HLG/LLG collection and no best-state rollback policy.
"""

import json
from pathlib import Path
from typing import Callable

from src.data_model import (
    DocumentationCoverageResult,
    DocumentationCoverageStatus,
    GlobalGoalCycleIteration,
    GlobalGoalCycleResult,
    GlobalGoalCycleStopReason,
    GlobalGoalEvaluationDecision,
    GlobalGoalEvaluationResult,
    HighLevelGoal,
    HighLevelGoalDuplicateCandidateSource,
    HighLevelGoalDuplicateResolution,
    HighLevelGoalGenerationAction,
    HighLevelGoalGenerationRequest,
    HighLevelGoalGenerationSource,
    HighLevelGoals,
    LowLevelGoal,
    LowLevelGoalRegenerationRequest,
    LowLevelGoals,
)
from src.bottom_up.goal_reconstructor import (
    normalize_goal_name,
    reconstruct_all_branches,
)
from src.bottom_up.global_goal_evaluator import (
    evaluate_all_branches,
    evaluate_documentation_coverage,
    save_documentation_coverage,
    save_global_evaluations,
)
from src.bottom_up.cycle_state import (
    _all_expected_branches_confirmed,
    _build_result,
    _build_state_signature,
    _build_structural_decisions,
)
from src.bottom_up.goal_update import (
    _apply_branch_high_level_generation,
    _append_coverage_generated_goals,
    _flatten_generated_high_level_goals,
    _goals_are_duplicates,
    _merge_selectively_regenerated_low_level_goals,
    _validate_generated_high_level_goals,
)
from src.bottom_up.semantic_similarity import states_semantically_equivalent
from src.llm_clients import MAX_SEMANTIC_RETRIES


DEFAULT_GLOBAL_CYCLE_MAX_ITERATIONS = 5
MAX_DOCUMENTATION_COVERAGE_NO_CHANGE_RECHECKS = 1


HighLevelGoalGenerator = Callable[
    [HighLevelGoalGenerationRequest],
    HighLevelGoals,
]
LowLevelGoalRegenerator = Callable[
    [LowLevelGoalRegenerationRequest],
    LowLevelGoals,
]


def load_global_evaluations(
    evaluation_file: str | Path,
    expected_branch_ids: set[str],
) -> dict[str, GlobalGoalEvaluationResult]:
    """Load one complete evaluator JSON and validate every expected branch."""
    path = Path(evaluation_file)
    payload = json.loads(path.read_text(encoding="utf-8"))

    if payload.get("status") != "READY_FOR_ORCHESTRATION":
        raise ValueError(
            f"Evaluator output '{path}' is not ready for orchestration. "
            f"Status={payload.get('status')!r}, "
            f"missing={payload.get('missing_branch_ids', [])}, "
            f"unexpected={payload.get('unexpected_branch_ids', [])}, "
            f"inconsistent={payload.get('inconsistent_branch_ids', [])}, "
            f"errors={payload.get('errors', {})}."
        )

    errors = payload.get("errors", {})
    if errors:
        raise ValueError(
            f"Evaluator output '{path}' contains unresolved errors: {errors}."
        )

    stored_expected = payload.get("expected_branch_ids")
    if not isinstance(stored_expected, list) or any(
        not isinstance(branch_id, str) for branch_id in stored_expected
    ):
        raise ValueError(
            f"Evaluator output '{path}' has no valid expected_branch_ids list."
        )

    stored_expected_set = set(stored_expected)
    if stored_expected_set != expected_branch_ids:
        raise ValueError(
            f"Evaluator output '{path}' was produced for a different branch "
            f"set. Expected={sorted(expected_branch_ids)}, "
            f"stored={sorted(stored_expected_set)}."
        )

    raw_evaluations = payload.get("evaluations")
    if not isinstance(raw_evaluations, dict):
        raise ValueError(
            f"Evaluator output '{path}' has no valid evaluations object."
        )

    raw_branch_ids = set(raw_evaluations)
    missing = expected_branch_ids - raw_branch_ids
    unexpected = raw_branch_ids - expected_branch_ids
    if missing or unexpected:
        raise ValueError(
            f"Evaluator output '{path}' is not complete. "
            f"Missing={sorted(missing)}, unexpected={sorted(unexpected)}."
        )

    evaluations: dict[str, GlobalGoalEvaluationResult] = {}
    for branch_id, raw_evaluation in raw_evaluations.items():
        evaluation = GlobalGoalEvaluationResult.model_validate(raw_evaluation)
        if evaluation.branch_id != branch_id:
            raise ValueError(
                f"Evaluator output '{path}' is inconsistent: dictionary key "
                f"'{branch_id}' does not match evaluation.branch_id "
                f"'{evaluation.branch_id}'."
            )
        evaluations[branch_id] = evaluation

    return evaluations


def load_documentation_coverage(
    coverage_file: str | Path,
) -> DocumentationCoverageResult:
    """Load a persisted documentation-coverage result."""
    path = Path(coverage_file)
    payload = json.loads(path.read_text(encoding="utf-8"))

    if payload.get("status") != "READY_FOR_ORCHESTRATION":
        raise ValueError(
            f"Coverage output '{path}' is not ready for orchestration."
        )

    raw_result = payload.get("documentation_coverage")
    if not isinstance(raw_result, dict):
        raise ValueError(
            f"Coverage output '{path}' has no valid documentation_coverage "
            "object."
        )

    return DocumentationCoverageResult.model_validate(raw_result)


def _collect_high_level_generation_requests(
    evaluations: dict[str, GlobalGoalEvaluationResult],
) -> list[HighLevelGoalGenerationRequest]:
    """Collect replacement requests emitted by unstable local branches."""
    requests: list[HighLevelGoalGenerationRequest] = []
    seen_request_ids: set[str] = set()

    for branch_id, evaluation in evaluations.items():
        if evaluation.decision == GlobalGoalEvaluationDecision.CONFIRM_BRANCH:
            if evaluation.generation_request is not None:
                raise ValueError(
                    f"Confirmed branch '{branch_id}' must not contain an HLG "
                    "generation request."
                )
            continue

        if (
            evaluation.decision
            != GlobalGoalEvaluationDecision.REGENERATE_HIGH_LEVEL_GOAL
        ):
            raise ValueError(
                f"Branch '{branch_id}' returned unsupported local decision "
                f"'{evaluation.decision.value}'."
            )

        request = evaluation.generation_request
        if request is None:
            raise ValueError(
                f"Branch '{branch_id}' requires HLG regeneration but contains "
                "no generation_request."
            )
        if request.source != HighLevelGoalGenerationSource.BRANCH_EVALUATION:
            raise ValueError(
                f"Request '{request.request_id}' has invalid source "
                f"'{request.source.value}'."
            )
        if (
            request.action
            != HighLevelGoalGenerationAction.REPLACE_EXISTING_HIGH_LEVEL_GOAL
        ):
            raise ValueError(
                f"Branch '{branch_id}' must use REPLACE_EXISTING_HIGH_LEVEL_GOAL."
            )
        if request.origin_branch_id != branch_id or request.target_branch_id != branch_id:
            raise ValueError(
                f"Request '{request.request_id}' must originate from and target "
                f"branch '{branch_id}'."
            )
        if request.request_id in seen_request_ids:
            raise ValueError(
                f"Duplicate HLG generation request id '{request.request_id}'."
            )
        seen_request_ids.add(request.request_id)
        requests.append(request)

    return requests


def _execute_high_level_generation_requests(
    generate_high_level_goals: HighLevelGoalGenerator,
    requests: list[HighLevelGoalGenerationRequest],
    existing_high_level_goals: dict[str, HighLevelGoal],
) -> tuple[
    dict[str, list[HighLevelGoal]],
    list[HighLevelGoalDuplicateResolution],
    str | None,
]:
    """Execute evaluated HLG ADD/REPLACE requests with duplicate guards.

    REPLACE is used only by local REGENERATE_HIGH_LEVEL_GOAL decisions. ADD is
    used only by documentation coverage. A replacement may resemble the HLG it
    replaces, but must not duplicate another surviving branch. Coverage ADDs
    are absorbed when they duplicate an existing or earlier generated HLG.
    """
    generated_by_request: dict[str, list[HighLevelGoal]] = {}
    duplicate_resolutions: list[HighLevelGoalDuplicateResolution] = []
    prior_generated: list[tuple[str, HighLevelGoal]] = []

    for request in requests:
        if request.source == HighLevelGoalGenerationSource.BRANCH_EVALUATION:
            if request.action != HighLevelGoalGenerationAction.REPLACE_EXISTING_HIGH_LEVEL_GOAL:
                return {}, duplicate_resolutions, (
                    f"ValueError: branch request '{request.request_id}' must "
                    "replace an existing HLG."
                )
        elif request.source == HighLevelGoalGenerationSource.DOCUMENTATION_COVERAGE:
            if request.action != HighLevelGoalGenerationAction.ADD_NEW_HIGH_LEVEL_GOAL:
                return {}, duplicate_resolutions, (
                    f"ValueError: coverage request '{request.request_id}' must "
                    "add a new HLG."
                )
        else:
            return {}, duplicate_resolutions, (
                f"ValueError: unsupported HLG request source "
                f"'{request.source.value}'."
            )

        try:
            generated = generate_high_level_goals(request)
        except Exception as exc:
            return {}, duplicate_resolutions, (
                f"{type(exc).__name__}: evaluated HLG request "
                f"'{request.request_id}' failed: {exc}"
            )

        validated_goals, validation_error = _validate_generated_high_level_goals(
            request=request,
            generated=generated,
        )
        if validation_error is not None or validated_goals is None:
            return {}, duplicate_resolutions, validation_error or (
                "ValueError: evaluated HLG callback returned no usable goal."
            )
        generated_goal = validated_goals[0]

        duplicate_existing: tuple[str, HighLevelGoal] | None = None
        for branch_id, existing_goal in existing_high_level_goals.items():
            if (
                request.action
                == HighLevelGoalGenerationAction.REPLACE_EXISTING_HIGH_LEVEL_GOAL
                and branch_id == request.target_branch_id
            ):
                continue
            if _goals_are_duplicates(generated_goal, existing_goal):
                duplicate_existing = (branch_id, existing_goal)
                break

        duplicate_prior: tuple[str, HighLevelGoal] | None = None
        for owner_request_id, prior_goal in prior_generated:
            if _goals_are_duplicates(generated_goal, prior_goal):
                duplicate_prior = (owner_request_id, prior_goal)
                break

        if request.action == HighLevelGoalGenerationAction.ADD_NEW_HIGH_LEVEL_GOAL:
            if duplicate_existing is not None:
                branch_id, existing_goal = duplicate_existing
                duplicate_resolutions.append(
                    HighLevelGoalDuplicateResolution(
                        request_id=request.request_id,
                        candidate_ids=["candidate_001", "candidate_002"],
                        candidate_sources={
                            "candidate_001": HighLevelGoalDuplicateCandidateSource.GENERATED,
                            "candidate_002": HighLevelGoalDuplicateCandidateSource.EXISTING,
                        },
                        candidate_branch_ids={
                            "candidate_001": None,
                            "candidate_002": branch_id,
                        },
                        selected_candidate_id="candidate_002",
                        selected_goal=existing_goal,
                        discarded_goals=[generated_goal],
                        rationale=(
                            "Deterministic coverage safety rule: an ADD request "
                            "cannot create a branch that duplicates an existing HLG."
                        ),
                    )
                )
                generated_by_request[request.request_id] = []
                continue

            if duplicate_prior is not None:
                _, prior_goal = duplicate_prior
                duplicate_resolutions.append(
                    HighLevelGoalDuplicateResolution(
                        request_id=request.request_id,
                        candidate_ids=["candidate_001", "candidate_002"],
                        candidate_sources={
                            "candidate_001": HighLevelGoalDuplicateCandidateSource.GENERATED,
                            "candidate_002": HighLevelGoalDuplicateCandidateSource.GENERATED,
                        },
                        candidate_branch_ids={
                            "candidate_001": None,
                            "candidate_002": None,
                        },
                        selected_candidate_id="candidate_002",
                        selected_goal=prior_goal,
                        discarded_goals=[generated_goal],
                        rationale=(
                            "Deterministic coverage safety rule: two ADD requests "
                            "produced the same intention; the earlier HLG is kept."
                        ),
                    )
                )
                generated_by_request[request.request_id] = []
                continue

        elif duplicate_existing is not None or duplicate_prior is not None:
            conflict_name = (
                duplicate_existing[1].name
                if duplicate_existing is not None
                else duplicate_prior[1].name
            )
            return {}, duplicate_resolutions, (
                "ValueError: evaluator-approved replacement HLG "
                f"'{generated_goal.name}' duplicates another surviving HLG "
                f"'{conflict_name}'. Replacement aborted."
            )

        generated_by_request[request.request_id] = [generated_goal]
        prior_generated.append((request.request_id, generated_goal))

    return generated_by_request, duplicate_resolutions, None


def _collect_branch_regeneration_targets(
    branch_map: dict[str, HighLevelGoal],
    evaluations: dict[str, GlobalGoalEvaluationResult],
    generated_by_request: dict[str, list[HighLevelGoal]],
) -> tuple[HighLevelGoals, set[str], dict[str, str]]:
    """Select replacement HLGs that must receive newly generated LLGs."""
    if set(branch_map) != set(evaluations):
        missing = set(branch_map) - set(evaluations)
        unexpected = set(evaluations) - set(branch_map)
        raise ValueError(
            "Cannot collect regeneration targets from an incomplete evaluation "
            f"set. Missing={sorted(missing)}, unexpected={sorted(unexpected)}."
        )

    targets: list[HighLevelGoal] = []
    replaced_parent_names: set[str] = set()
    guidance_by_parent_name: dict[str, str] = {}

    for branch_id, original in branch_map.items():
        evaluation = evaluations[branch_id]
        if evaluation.decision == GlobalGoalEvaluationDecision.CONFIRM_BRANCH:
            continue
        if (
            evaluation.decision
            != GlobalGoalEvaluationDecision.REGENERATE_HIGH_LEVEL_GOAL
        ):
            raise ValueError(
                f"Branch '{branch_id}' returned unsupported decision "
                f"'{evaluation.decision.value}'."
            )

        request = evaluation.generation_request
        if request is None:
            raise ValueError(
                f"Branch '{branch_id}' has no replacement generation request."
            )
        replacements = generated_by_request.get(request.request_id)
        if replacements is None or len(replacements) != 1:
            raise ValueError(
                f"Branch '{branch_id}' has no unique evaluator-approved "
                "replacement HLG."
            )

        replacement = replacements[0]
        targets.append(replacement)
        replaced_parent_names.add(normalize_goal_name(original.name))

        guidance = (
            request.generator_guidance
            or evaluation.rationale
            or "Generate a complete operational decomposition for this HLG."
        ).strip()
        if guidance:
            guidance_by_parent_name[replacement.name] = guidance

    return HighLevelGoals(goals=targets), replaced_parent_names, guidance_by_parent_name


def _regenerate_selected_branches(
    regenerate_low_level_goals: LowLevelGoalRegenerator,
    targets: HighLevelGoals,
    current_low_level_goals: LowLevelGoals,
    replaced_parent_names: set[str],
    guidance_by_parent_name: dict[str, str] | None = None,
) -> tuple[LowLevelGoals | None, str | None]:
    """Run the original evaluated LLG callback only for selected HLGs."""
    if not targets.goals:
        merged = _merge_selectively_regenerated_low_level_goals(
            current_low_level_goals=current_low_level_goals,
            regenerated_low_level_goals=LowLevelGoals(low_level_goals=[]),
            replaced_parent_names=replaced_parent_names,
        )
        return merged, None

    targets_by_name: dict[str, HighLevelGoal] = {}
    for target in targets.goals:
        normalized_name = normalize_goal_name(target.name)
        if normalized_name in targets_by_name:
            return None, (
                "ValueError: selective regeneration targets contain duplicate "
                f"parent name '{target.name}' after normalization."
            )
        targets_by_name[normalized_name] = target

    expected_parent_names = set(targets_by_name)
    pending_parent_names = set(expected_parent_names)
    accepted_by_parent: dict[str, list[LowLevelGoal]] = {}
    last_missing = sorted(pending_parent_names)

    for _ in range(MAX_SEMANTIC_RETRIES + 1):
        pending_targets = HighLevelGoals(
            goals=[
                target
                for normalized_name, target in targets_by_name.items()
                if normalized_name in pending_parent_names
            ]
        )
        pending_guidance = {
            goal.name: (guidance_by_parent_name or {}).get(goal.name, "")
            for goal in pending_targets.goals
            if (guidance_by_parent_name or {}).get(goal.name, "").strip()
        }
        regeneration_request = LowLevelGoalRegenerationRequest(
            high_level_goals=pending_targets,
            guidance_by_parent_name=pending_guidance,
        )

        try:
            regenerated = regenerate_low_level_goals(regeneration_request)
        except Exception as exc:
            return None, f"{type(exc).__name__}: {exc}"

        if not isinstance(regenerated, LowLevelGoals):
            return None, (
                "TypeError: regenerate_low_level_goals must return a "
                "LowLevelGoals instance."
            )

        returned_by_parent: dict[str, list[LowLevelGoal]] = {}
        for goal in regenerated.low_level_goals:
            parent_name = normalize_goal_name(goal.high_level_associated.name)
            returned_by_parent.setdefault(parent_name, []).append(goal)

        returned_parent_names = set(returned_by_parent)
        unexpected = returned_parent_names - pending_parent_names
        if unexpected:
            return None, (
                "ValueError: selective regeneration returned LLGs for parent "
                "goals that were not requested in this retry. "
                f"Unexpected={sorted(unexpected)}, "
                f"requested={sorted(pending_parent_names)}."
            )

        for parent_name, goals in returned_by_parent.items():
            if goals:
                accepted_by_parent[parent_name] = goals
                pending_parent_names.discard(parent_name)

        if not pending_parent_names:
            break

        last_missing = sorted(pending_parent_names)

    if pending_parent_names:
        return None, (
            "ValueError: selective regeneration did not return a complete LLG "
            "decomposition after semantic retries. "
            f"Missing={last_missing}, expected={sorted(expected_parent_names)}."
        )

    regenerated_complete = LowLevelGoals(
        low_level_goals=[
            goal
            for normalized_name in targets_by_name
            for goal in accepted_by_parent[normalized_name]
        ]
    )
    merged = _merge_selectively_regenerated_low_level_goals(
        current_low_level_goals=current_low_level_goals,
        regenerated_low_level_goals=regenerated_complete,
        replaced_parent_names=replaced_parent_names,
    )
    return merged, None


def run_global_goal_cycle(
    project_description: str,
    initial_high_level_goals: HighLevelGoals,
    initial_low_level_goals: LowLevelGoals,
    generate_high_level_goals: HighLevelGoalGenerator,
    regenerate_low_level_goals: LowLevelGoalRegenerator,
    evaluation_output_directory: str | Path,
    max_iterations: int = DEFAULT_GLOBAL_CYCLE_MAX_ITERATIONS,
) -> GlobalGoalCycleResult:
    """Execute the HLG-regeneration bottom-up feedback cycle."""
    if max_iterations < 1:
        raise ValueError("max_iterations must be greater than or equal to 1.")

    output_directory = Path(evaluation_output_directory)
    output_directory.mkdir(parents=True, exist_ok=True)

    current_high_level_goals = initial_high_level_goals.model_copy(deep=True)
    current_low_level_goals = initial_low_level_goals.model_copy(deep=True)

    iteration_traces: list[GlobalGoalCycleIteration] = []
    seen_state_signatures: dict[str, str] = {}
    seen_states: list[
        tuple[HighLevelGoals, LowLevelGoals, dict[str, dict[str, object]]]
    ] = []
    all_added_high_level_goals: list[HighLevelGoal] = []

    last_bottom_up_errors: dict[str, str] = {}
    last_evaluation_errors: dict[str, str] = {}
    last_empty_branches: list[str] = []

    for iteration_number in range(1, max_iterations + 1):
        (
            reconstructed_goals,
            branch_map,
            bottom_up_errors,
            empty_branches,
            branch_traceability,
        ) = reconstruct_all_branches(
            high_level_goals=current_high_level_goals,
            low_level_goals=current_low_level_goals,
        )

        evaluations, evaluation_errors = evaluate_all_branches(
            project_description=project_description,
            existing_high_level_goals=branch_map,
            reconstructed_high_level_goals=reconstructed_goals,
            empty_branches=empty_branches,
        )

        evaluation_file = (
            output_directory
            / f"iteration_{iteration_number:03d}_global_evaluations.json"
        )
        save_global_evaluations(
            output_file=evaluation_file,
            expected_high_level_goals=branch_map,
            evaluations=evaluations,
            errors=evaluation_errors,
        )

        try:
            evaluations = load_global_evaluations(
                evaluation_file=evaluation_file,
                expected_branch_ids=set(branch_map),
            )
        except Exception as exc:
            evaluation_errors = {
                **evaluation_errors,
                "evaluation_json": f"{type(exc).__name__}: {exc}",
            }

        all_branches_confirmed = _all_expected_branches_confirmed(
            branch_map=branch_map,
            evaluations=evaluations,
            reconstruction_errors=bottom_up_errors,
            evaluation_errors=evaluation_errors,
            empty_branches=empty_branches,
        )

        state_signature, state_canonical_json = _build_state_signature(
            high_level_goals=current_high_level_goals,
            low_level_goals=current_low_level_goals,
            decisions=evaluations,
        )

        trace = GlobalGoalCycleIteration(
            iteration=iteration_number,
            input_high_level_goals=current_high_level_goals,
            input_low_level_goals=current_low_level_goals,
            branch_traceability=branch_traceability,
            reconstructed_high_level_goals=reconstructed_goals,
            bottom_up_errors=bottom_up_errors,
            empty_branches=empty_branches,
            global_evaluations=evaluations,
            global_evaluation_errors=evaluation_errors,
            all_branches_confirmed=all_branches_confirmed,
            requires_regeneration=not all_branches_confirmed,
            state_signature=state_signature,
        )
        iteration_traces.append(trace)

        last_bottom_up_errors = bottom_up_errors
        last_evaluation_errors = evaluation_errors
        last_empty_branches = empty_branches

        previous_canonical_json = seen_state_signatures.get(state_signature)
        exact_repeated_state = (
            previous_canonical_json is not None
            and previous_canonical_json == state_canonical_json
        )

        if exact_repeated_state:
            return _build_result(
                converged=False,
                stop_reason=GlobalGoalCycleStopReason.REPEATED_STATE_DETECTED,
                completed_iterations=iteration_number,
                max_iterations=max_iterations,
                current_high_level_goals=current_high_level_goals,
                current_low_level_goals=current_low_level_goals,
                iterations=iteration_traces,
                added_high_level_goals=all_added_high_level_goals,
                bottom_up_errors=bottom_up_errors,
                evaluation_errors=evaluation_errors,
                empty_branches=empty_branches,
            )

        current_structural_decisions = _build_structural_decisions(evaluations)
        semantically_repeated_state = any(
            previous_structural_decisions == current_structural_decisions
            and states_semantically_equivalent(
                high_level_goals_a=current_high_level_goals,
                high_level_goals_b=previous_high_level_goals,
                low_level_goals_a=current_low_level_goals,
                low_level_goals_b=previous_low_level_goals,
            )
            for (
                previous_high_level_goals,
                previous_low_level_goals,
                previous_structural_decisions,
            ) in seen_states
        )

        if semantically_repeated_state:
            return _build_result(
                converged=False,
                stop_reason=(
                    GlobalGoalCycleStopReason.SEMANTIC_REPEATED_STATE_DETECTED
                ),
                completed_iterations=iteration_number,
                max_iterations=max_iterations,
                current_high_level_goals=current_high_level_goals,
                current_low_level_goals=current_low_level_goals,
                iterations=iteration_traces,
                added_high_level_goals=all_added_high_level_goals,
                bottom_up_errors=bottom_up_errors,
                evaluation_errors=evaluation_errors,
                empty_branches=empty_branches,
            )

        seen_state_signatures[state_signature] = state_canonical_json
        seen_states.append(
            (
                current_high_level_goals.model_copy(deep=True),
                current_low_level_goals.model_copy(deep=True),
                current_structural_decisions,
            )
        )

        if bottom_up_errors:
            return _build_result(
                converged=False,
                stop_reason=(
                    GlobalGoalCycleStopReason.BOTTOM_UP_RECONSTRUCTION_FAILED
                ),
                completed_iterations=iteration_number,
                max_iterations=max_iterations,
                current_high_level_goals=current_high_level_goals,
                current_low_level_goals=current_low_level_goals,
                iterations=iteration_traces,
                added_high_level_goals=all_added_high_level_goals,
                bottom_up_errors=bottom_up_errors,
                evaluation_errors=evaluation_errors,
                empty_branches=empty_branches,
            )

        if evaluation_errors:
            return _build_result(
                converged=False,
                stop_reason=GlobalGoalCycleStopReason.GLOBAL_EVALUATION_FAILED,
                completed_iterations=iteration_number,
                max_iterations=max_iterations,
                current_high_level_goals=current_high_level_goals,
                current_low_level_goals=current_low_level_goals,
                iterations=iteration_traces,
                added_high_level_goals=all_added_high_level_goals,
                evaluation_errors=evaluation_errors,
                empty_branches=empty_branches,
            )

        if all_branches_confirmed:
            coverage_recheck_index = 0

            while True:
                try:
                    coverage = evaluate_documentation_coverage(
                        project_description=project_description,
                        current_high_level_goals=current_high_level_goals,
                        reconstructed_high_level_goals=reconstructed_goals,
                    )

                    if coverage_recheck_index == 0:
                        coverage_file = (
                            output_directory
                            / (
                                f"iteration_{iteration_number:03d}_"
                                "documentation_coverage.json"
                            )
                        )
                    else:
                        coverage_file = (
                            output_directory
                            / (
                                f"iteration_{iteration_number:03d}_"
                                "documentation_coverage_recheck_"
                                f"{coverage_recheck_index:03d}.json"
                            )
                        )

                    save_documentation_coverage(coverage_file, coverage)
                    coverage = load_documentation_coverage(coverage_file)
                except Exception as exc:
                    coverage_error = f"{type(exc).__name__}: {exc}"
                    trace.documentation_coverage_error = coverage_error
                    return _build_result(
                        converged=False,
                        stop_reason=(
                            GlobalGoalCycleStopReason
                            .DOCUMENTATION_COVERAGE_EVALUATION_FAILED
                        ),
                        completed_iterations=iteration_number,
                        max_iterations=max_iterations,
                        current_high_level_goals=current_high_level_goals,
                        current_low_level_goals=current_low_level_goals,
                        iterations=iteration_traces,
                        added_high_level_goals=all_added_high_level_goals,
                        coverage_error=coverage_error,
                    )

                if coverage_recheck_index == 0:
                    trace.documentation_coverage = coverage
                else:
                    trace.documentation_coverage_rechecks.append(coverage)

                trace.documentation_fully_covered = (
                    coverage.status == DocumentationCoverageStatus.COMPLETE
                )

                if coverage.status == DocumentationCoverageStatus.COMPLETE:
                    if coverage_recheck_index > 0:
                        trace.updated_high_level_goals = current_high_level_goals
                        trace.regenerated_low_level_goals = current_low_level_goals
                        trace.requires_regeneration = False

                    return _build_result(
                        converged=True,
                        stop_reason=(
                            GlobalGoalCycleStopReason
                            .ALL_BRANCHES_CONFIRMED_AND_DOCUMENTATION_COVERED
                        ),
                        completed_iterations=iteration_number,
                        max_iterations=max_iterations,
                        current_high_level_goals=current_high_level_goals,
                        current_low_level_goals=current_low_level_goals,
                        iterations=iteration_traces,
                        added_high_level_goals=all_added_high_level_goals,
                    )

                generation_requests = coverage.generation_requests
                trace.high_level_generation_requests.extend(generation_requests)

                (
                    generated_by_request,
                    duplicate_resolutions,
                    high_level_error,
                ) = _execute_high_level_generation_requests(
                    generate_high_level_goals=generate_high_level_goals,
                    requests=generation_requests,
                    existing_high_level_goals=branch_map,
                )
                trace.high_level_duplicate_resolutions.extend(
                    duplicate_resolutions
                )

                if high_level_error is not None:
                    trace.high_level_regeneration_error = high_level_error
                    return _build_result(
                        converged=False,
                        stop_reason=(
                            GlobalGoalCycleStopReason.HIGH_LEVEL_REGENERATION_FAILED
                        ),
                        completed_iterations=iteration_number,
                        max_iterations=max_iterations,
                        current_high_level_goals=current_high_level_goals,
                        current_low_level_goals=current_low_level_goals,
                        iterations=iteration_traces,
                        added_high_level_goals=all_added_high_level_goals,
                        high_level_regeneration_error=high_level_error,
                    )

                surviving_generated_goals = _flatten_generated_high_level_goals(
                    generated_by_request
                )
                previously_recorded_generated = (
                    trace.generated_high_level_goals.goals
                    if trace.generated_high_level_goals is not None
                    else []
                )
                trace.generated_high_level_goals = HighLevelGoals(
                    goals=[
                        *previously_recorded_generated,
                        *surviving_generated_goals,
                    ]
                )

                try:
                    updated_high_level_goals, added_goals = (
                        _append_coverage_generated_goals(
                            current_high_level_goals=current_high_level_goals,
                            requests=generation_requests,
                            generated_by_request=generated_by_request,
                        )
                    )
                except Exception as exc:
                    high_level_error = f"{type(exc).__name__}: {exc}"
                    trace.high_level_regeneration_error = high_level_error
                    return _build_result(
                        converged=False,
                        stop_reason=(
                            GlobalGoalCycleStopReason.HIGH_LEVEL_REGENERATION_FAILED
                        ),
                        completed_iterations=iteration_number,
                        max_iterations=max_iterations,
                        current_high_level_goals=current_high_level_goals,
                        current_low_level_goals=current_low_level_goals,
                        iterations=iteration_traces,
                        added_high_level_goals=all_added_high_level_goals,
                        high_level_regeneration_error=high_level_error,
                    )

                trace.newly_added_high_level_goals.extend(added_goals)
                trace.updated_high_level_goals = updated_high_level_goals
                all_added_high_level_goals.extend(added_goals)

                coverage_no_hlg_state_change = (
                    bool(generation_requests)
                    and not added_goals
                    and all(
                        not generated_by_request.get(request.request_id, [])
                        for request in generation_requests
                    )
                )

                if coverage_no_hlg_state_change:
                    trace.documentation_fully_covered = False
                    trace.requires_regeneration = False
                    trace.updated_high_level_goals = current_high_level_goals
                    trace.regenerated_low_level_goals = current_low_level_goals

                    if (
                        coverage_recheck_index
                        >= MAX_DOCUMENTATION_COVERAGE_NO_CHANGE_RECHECKS
                    ):
                        return _build_result(
                            converged=False,
                            stop_reason=(
                                GlobalGoalCycleStopReason.REPEATED_STATE_DETECTED
                            ),
                            completed_iterations=iteration_number,
                            max_iterations=max_iterations,
                            current_high_level_goals=current_high_level_goals,
                            current_low_level_goals=current_low_level_goals,
                            iterations=iteration_traces,
                            added_high_level_goals=all_added_high_level_goals,
                        )

                    coverage_recheck_index += 1
                    continue

                trace.requires_regeneration = True
                targets = HighLevelGoals(goals=added_goals)
                coverage_guidance_by_parent_name = {
                    goal.name: (request.generator_guidance or request.rationale)
                    for request in generation_requests
                    for goal in generated_by_request.get(request.request_id, [])
                }

                merged, regeneration_error = _regenerate_selected_branches(
                    regenerate_low_level_goals=regenerate_low_level_goals,
                    targets=targets,
                    current_low_level_goals=current_low_level_goals,
                    replaced_parent_names=set(),
                    guidance_by_parent_name=coverage_guidance_by_parent_name,
                )

                if regeneration_error is not None or merged is None:
                    error = regeneration_error or (
                        "Unknown selective regeneration error."
                    )
                    trace.global_evaluation_errors[
                        "low_level_regeneration"
                    ] = error
                    return _build_result(
                        converged=False,
                        stop_reason=(
                            GlobalGoalCycleStopReason.LOW_LEVEL_REGENERATION_FAILED
                        ),
                        completed_iterations=iteration_number,
                        max_iterations=max_iterations,
                        current_high_level_goals=current_high_level_goals,
                        current_low_level_goals=current_low_level_goals,
                        iterations=iteration_traces,
                        added_high_level_goals=all_added_high_level_goals,
                        evaluation_errors={"low_level_regeneration": error},
                    )

                trace.regenerated_low_level_goals = merged
                current_high_level_goals = updated_high_level_goals
                current_low_level_goals = merged
                break

            continue

        # Local feedback path: every unstable branch is regenerated from HLG
        # level. The replacement HLG is generated/evaluated first and then its
        # LLG decomposition is ALWAYS generated/evaluated before the next cycle.
        try:
            generation_requests = _collect_high_level_generation_requests(
                evaluations
            )
        except Exception as exc:
            high_level_error = f"{type(exc).__name__}: {exc}"
            trace.high_level_regeneration_error = high_level_error
            return _build_result(
                converged=False,
                stop_reason=GlobalGoalCycleStopReason.HIGH_LEVEL_REGENERATION_FAILED,
                completed_iterations=iteration_number,
                max_iterations=max_iterations,
                current_high_level_goals=current_high_level_goals,
                current_low_level_goals=current_low_level_goals,
                iterations=iteration_traces,
                added_high_level_goals=all_added_high_level_goals,
                evaluation_errors=evaluation_errors,
                empty_branches=empty_branches,
                high_level_regeneration_error=high_level_error,
            )

        trace.high_level_generation_requests = generation_requests

        (
            generated_by_request,
            duplicate_resolutions,
            high_level_error,
        ) = _execute_high_level_generation_requests(
            generate_high_level_goals=generate_high_level_goals,
            requests=generation_requests,
            existing_high_level_goals=branch_map,
        )
        trace.high_level_duplicate_resolutions = duplicate_resolutions

        if high_level_error is not None:
            trace.high_level_regeneration_error = high_level_error
            return _build_result(
                converged=False,
                stop_reason=GlobalGoalCycleStopReason.HIGH_LEVEL_REGENERATION_FAILED,
                completed_iterations=iteration_number,
                max_iterations=max_iterations,
                current_high_level_goals=current_high_level_goals,
                current_low_level_goals=current_low_level_goals,
                iterations=iteration_traces,
                added_high_level_goals=all_added_high_level_goals,
                evaluation_errors=evaluation_errors,
                empty_branches=empty_branches,
                high_level_regeneration_error=high_level_error,
            )

        trace.generated_high_level_goals = HighLevelGoals(
            goals=_flatten_generated_high_level_goals(generated_by_request)
        )

        try:
            updated_high_level_goals = _apply_branch_high_level_generation(
                existing_high_level_goals=branch_map,
                requests=generation_requests,
                generated_by_request=generated_by_request,
            )
            (
                targets,
                replaced_parent_names,
                guidance_by_parent_name,
            ) = _collect_branch_regeneration_targets(
                branch_map=branch_map,
                evaluations=evaluations,
                generated_by_request=generated_by_request,
            )
        except Exception as exc:
            high_level_error = f"{type(exc).__name__}: {exc}"
            trace.high_level_regeneration_error = high_level_error
            return _build_result(
                converged=False,
                stop_reason=GlobalGoalCycleStopReason.HIGH_LEVEL_REGENERATION_FAILED,
                completed_iterations=iteration_number,
                max_iterations=max_iterations,
                current_high_level_goals=current_high_level_goals,
                current_low_level_goals=current_low_level_goals,
                iterations=iteration_traces,
                added_high_level_goals=all_added_high_level_goals,
                evaluation_errors=evaluation_errors,
                empty_branches=empty_branches,
                high_level_regeneration_error=high_level_error,
            )

        trace.updated_high_level_goals = updated_high_level_goals
        trace.requires_regeneration = True

        merged, regeneration_error = _regenerate_selected_branches(
            regenerate_low_level_goals=regenerate_low_level_goals,
            targets=targets,
            current_low_level_goals=current_low_level_goals,
            replaced_parent_names=replaced_parent_names,
            guidance_by_parent_name=guidance_by_parent_name,
        )

        if regeneration_error is not None or merged is None:
            error = regeneration_error or "Unknown selective regeneration error."
            trace.global_evaluation_errors["low_level_regeneration"] = error
            return _build_result(
                converged=False,
                stop_reason=GlobalGoalCycleStopReason.LOW_LEVEL_REGENERATION_FAILED,
                completed_iterations=iteration_number,
                max_iterations=max_iterations,
                current_high_level_goals=current_high_level_goals,
                current_low_level_goals=current_low_level_goals,
                iterations=iteration_traces,
                added_high_level_goals=all_added_high_level_goals,
                evaluation_errors={
                    **evaluation_errors,
                    "low_level_regeneration": error,
                },
                empty_branches=empty_branches,
            )

        trace.regenerated_low_level_goals = merged
        current_high_level_goals = updated_high_level_goals
        current_low_level_goals = merged

    return _build_result(
        converged=False,
        stop_reason=GlobalGoalCycleStopReason.MAX_ITERATIONS_REACHED,
        completed_iterations=max_iterations,
        max_iterations=max_iterations,
        current_high_level_goals=current_high_level_goals,
        current_low_level_goals=current_low_level_goals,
        iterations=iteration_traces,
        added_high_level_goals=all_added_high_level_goals,
        bottom_up_errors=last_bottom_up_errors,
        evaluation_errors=last_evaluation_errors,
        empty_branches=last_empty_branches,
    )
