from typing import Literal
from pydantic import BaseModel, Field
""" 
This data model is designed for structured outputs generated by an LLM.
It structures system goals, actors, and APIs, defining a hierarchy where 
high-level goals encompass multiple low-level goals, which in turn are 
associated with specific APIs.
"""

class DocumentDescription(BaseModel):
    description: str

class Actor(BaseModel):
    name: str
    description: str

class Actors(BaseModel):
    actors: list[Actor]

class HighLevelGoal(BaseModel):
    name: str
    description: str
    actor: Actor

class HighLevelGoals(BaseModel):
    goals: list[HighLevelGoal]

class LowLevelGoal(BaseModel):
    name: str
    description: str
    high_level_associated: HighLevelGoal

class LowLevelGoals(BaseModel):
    low_level_goals: list[LowLevelGoal]

class API(BaseModel):
    api_name: str
    api_path: str
    description: str
    request_type: str

class APIMapping(BaseModel):
    APIs: list[API]
    low_level_goal: LowLevelGoal


class Critique(BaseModel):
    score: float
    comment: str


class BottomUpHighLevelGoalLLMOutput(BaseModel):
    """
    Structured output requested from the LLM for the Bottom-up High-Level Goal
    Generator. Contains only the semantic content produced by the model: no
    identifier or traceability metadata is generated by the LLM itself.
    """
    reconstructed_high_level_goal: str
    abstraction_rationale: str
    supporting_low_level_goal_ids: list[str]
    cohesion: Literal["high", "medium", "low"]
    confidence: Literal["high", "medium", "low"]


class BottomUpHighLevelGoal(BaseModel):
    """
    Final result of the Bottom-up High-Level Goal Generator: the LLM-generated
    fields combined with deterministic metadata (branch_id, source_low_level_goal_ids)
    computed by Python. Does not carry any reference to the original parent
    high-level goal; that traceability is kept only by the orchestrator.
    """
    branch_id: str
    reconstructed_high_level_goal: str
    abstraction_rationale: str
    supporting_low_level_goal_ids: list[str]
    source_low_level_goal_ids: list[str]
    cohesion: Literal["high", "medium", "low"]
    confidence: Literal["high", "medium", "low"]


# ---------------------------------------------------------------------------
# Global Goal Evaluator
# ---------------------------------------------------------------------------

GlobalGoalEvaluationDecision = Literal[
    "CONFIRM_BRANCH",
    "REGENERATE_LOW_LEVEL_GOALS",
    "MATCHES_OTHER_HIGH_LEVEL_GOAL",
    "ADD_NEW_HIGH_LEVEL_GOAL",
    "REWRITE_ORIGINAL_HIGH_LEVEL_GOAL",
]


class GlobalGoalEvaluationLLMOutput(BaseModel):
    """
    Structured output requested from the LLM for the Global Goal Evaluator.
    The LLM never authors identifiers other than a reference to an existing
    branch_id; Python resolves references and computes deterministic
    metadata (operational_action, requires_low_level_regeneration) afterwards.
    """
    decision: GlobalGoalEvaluationDecision
    matched_high_level_goal_id: str | None = None
    new_or_replacement_goal_name: str | None = None
    new_or_replacement_goal_description: str | None = None
    rationale: str


class GlobalGoalEvaluationResult(BaseModel):
    """
    Final result of the Global Goal Evaluator for a single branch: the
    LLM-generated fields combined with deterministic metadata computed by
    Python.
    """
    branch_id: str
    decision: GlobalGoalEvaluationDecision
    original_high_level_goal: HighLevelGoal
    reconstructed_high_level_goal: str
    matched_high_level_goal: HighLevelGoal | None = None
    new_or_replacement_high_level_goal: HighLevelGoal | None = None
    rationale: str
    operational_action: str
    requires_low_level_regeneration: bool


# ---------------------------------------------------------------------------
# Global refinement-abstraction-verification cycle
# ---------------------------------------------------------------------------

GlobalGoalCycleStopReason = Literal[
    "ALL_BRANCHES_CONFIRMED",
    "MAX_ITERATIONS_REACHED",
    "REPEATED_STATE_DETECTED",
    "BOTTOM_UP_RECONSTRUCTION_FAILED",
    "GLOBAL_EVALUATION_FAILED",
    "LOW_LEVEL_REGENERATION_FAILED",
]


class GlobalGoalCycleIteration(BaseModel):
    """
    Complete trace of one outer refinement-abstraction-verification iteration.

    Each iteration starts from a high-level goal collection and its associated
    low-level decomposition. It then records the bottom-up reconstructions,
    the global evaluations, the updated high-level goals, and any regenerated
    low-level goals.
    """

    iteration: int

    input_high_level_goals: HighLevelGoals
    input_low_level_goals: LowLevelGoals

    branch_traceability: dict[str, dict[str, object]] = Field(
        default_factory=dict
    )

    reconstructed_high_level_goals: dict[
        str,
        BottomUpHighLevelGoal,
    ] = Field(default_factory=dict)

    bottom_up_errors: dict[str, str] = Field(default_factory=dict)
    empty_branches: list[str] = Field(default_factory=list)

    global_evaluations: dict[
        str,
        GlobalGoalEvaluationResult,
    ] = Field(default_factory=dict)

    global_evaluation_errors: dict[str, str] = Field(
        default_factory=dict
    )

    updated_high_level_goals: HighLevelGoals | None = None
    regenerated_low_level_goals: LowLevelGoals | None = None

    all_branches_confirmed: bool = False
    requires_regeneration: bool = False

    state_signature: str


class GlobalGoalCycleResult(BaseModel):
    """
    Final result of the bounded outer feedback loop.

    It stores the final goal collections, the convergence status, the reason
    for termination, all iteration traces, and unresolved errors.
    """

    converged: bool
    stop_reason: GlobalGoalCycleStopReason
    completed_iterations: int
    max_iterations: int

    final_high_level_goals: HighLevelGoals
    final_low_level_goals: LowLevelGoals

    iterations: list[GlobalGoalCycleIteration] = Field(
        default_factory=list
    )

    unresolved_bottom_up_errors: dict[str, str] = Field(
        default_factory=dict
    )
    unresolved_global_evaluation_errors: dict[str, str] = Field(
        default_factory=dict
    )
    unresolved_empty_branches: list[str] = Field(
        default_factory=list
    )