from typing import Literal

from pydantic import BaseModel, Field, model_validator

"""
Structured data models used by the top-down and bottom-up goal pipeline.

The Global Goal Evaluator does not generate final high-level goals. When a
high-level goal must be added or replaced, it produces a generation request
whose ``generator_input`` contains exactly the information required by the
existing top-down HLG generator: a project description and a set of actors.

The orchestrator is responsible for:
- forwarding ``generator_input`` to the original top-down HLG generator;
- adding or replacing the generated goals according to ``action``;
- regenerating the corresponding low-level goals when required.
"""


class DocumentDescription(BaseModel):
    description: str


class Actor(BaseModel):
    name: str
    description: str


class Actors(BaseModel):
    actors: list[Actor]


class HighLevelGoal(BaseModel):
    name: str
    description: str
    actor: Actor


class HighLevelGoals(BaseModel):
    goals: list[HighLevelGoal]


class LowLevelGoal(BaseModel):
    name: str
    description: str
    high_level_associated: HighLevelGoal


class LowLevelGoals(BaseModel):
    low_level_goals: list[LowLevelGoal]


class API(BaseModel):
    api_name: str
    api_path: str
    description: str
    request_type: str


class APIMapping(BaseModel):
    APIs: list[API]
    low_level_goal: LowLevelGoal


class Critique(BaseModel):
    score: float
    comment: str


# ---------------------------------------------------------------------------
# Bottom-up High-Level Goal reconstruction
# ---------------------------------------------------------------------------


class BottomUpHighLevelGoalLLMOutput(BaseModel):
    """
    Semantic output requested from the bottom-up High-Level Goal Generator.

    Identifiers and traceability metadata are added deterministically by
    Python and are not generated by the LLM.
    """

    reconstructed_high_level_goal: str
    abstraction_rationale: str
    supporting_low_level_goal_ids: list[str]
    cohesion: Literal["high", "medium", "low"]
    confidence: Literal["high", "medium", "low"]


class BottomUpHighLevelGoal(BaseModel):
    """
    Final bottom-up reconstruction result for one branch.

    The original parent HLG is deliberately excluded. Parent traceability is
    maintained separately by the orchestrator.
    """

    branch_id: str
    reconstructed_high_level_goal: str
    abstraction_rationale: str
    supporting_low_level_goal_ids: list[str]
    source_low_level_goal_ids: list[str]
    cohesion: Literal["high", "medium", "low"]
    confidence: Literal["high", "medium", "low"]


# ---------------------------------------------------------------------------
# Requests for the existing top-down HLG generator
# ---------------------------------------------------------------------------


HighLevelGoalGenerationAction = Literal[
    "ADD_NEW_HIGH_LEVEL_GOAL",
    "REPLACE_EXISTING_HIGH_LEVEL_GOAL",
]

HighLevelGoalGenerationSource = Literal[
    "BRANCH_EVALUATION",
    "DOCUMENTATION_COVERAGE",
]


class HighLevelGoalGeneratorInput(BaseModel):
    """
    Input forwarded to the existing top-down ``generate_high_level_goals``
    function.

    The field names intentionally match the original function parameters:
    ``project_description`` and ``actors``. No information about evaluation,
    correction, replacement, branch identifiers, or previous attempts is
    exposed to the generator.
    """

    project_description: str
    actors: Actors

    @model_validator(mode="after")
    def validate_generator_input(self) -> "HighLevelGoalGeneratorInput":
        if not self.project_description.strip():
            raise ValueError("project_description must be a non-empty string.")

        if not self.actors.actors:
            raise ValueError("actors must contain at least one actor.")

        return self


class HighLevelGoalGenerationRequest(BaseModel):
    """
    One validated request to generate HLGs through the original top-down block.

    ``generator_input`` is the only part forwarded to the HLG generator.
    ``action`` and ``target_branch_id`` are orchestration metadata and are never
    shown to the generator.
    """

    request_id: str
    action: HighLevelGoalGenerationAction
    source: HighLevelGoalGenerationSource
    generator_input: HighLevelGoalGeneratorInput

    target_branch_id: str | None = None
    origin_branch_id: str | None = None
    rationale: str

    @model_validator(mode="after")
    def validate_generation_request(self) -> "HighLevelGoalGenerationRequest":
        if not self.request_id.strip():
            raise ValueError("request_id must be a non-empty string.")

        if not self.rationale.strip():
            raise ValueError("rationale must be a non-empty string.")

        if self.action == "REPLACE_EXISTING_HIGH_LEVEL_GOAL":
            if not self.target_branch_id:
                raise ValueError(
                    "REPLACE_EXISTING_HIGH_LEVEL_GOAL requires "
                    "target_branch_id."
                )
        elif self.target_branch_id is not None:
            raise ValueError(
                "target_branch_id must be null for ADD_NEW_HIGH_LEVEL_GOAL."
            )

        if self.source == "BRANCH_EVALUATION" and not self.origin_branch_id:
            raise ValueError(
                "A BRANCH_EVALUATION request requires origin_branch_id."
            )

        return self


# ---------------------------------------------------------------------------
# Global Goal Evaluator
# ---------------------------------------------------------------------------


GlobalGoalEvaluationDecision = Literal[
    "CONFIRM_BRANCH",
    "REGENERATE_LOW_LEVEL_GOALS",
    "MATCHES_OTHER_HIGH_LEVEL_GOAL",
    "ADD_NEW_HIGH_LEVEL_GOAL",
    "REWRITE_ORIGINAL_HIGH_LEVEL_GOAL",
]


class GlobalGoalEvaluationLLMOutput(BaseModel):
    """
    Structured output requested from the Global Goal Evaluator LLM.

    The evaluator decides what must happen. For ADD/REWRITE decisions it
    provides a focused description of the documented intention that must be
    passed to the normal top-down HLG generator. It does not generate the final
    HLG name or description.
    """

    decision: GlobalGoalEvaluationDecision
    matched_high_level_goal_id: str | None = None
    generation_project_description: str | None = None
    rationale: str

    @model_validator(mode="after")
    def validate_decision_fields(self) -> "GlobalGoalEvaluationLLMOutput":
        if (
            self.decision != "MATCHES_OTHER_HIGH_LEVEL_GOAL"
            and self.matched_high_level_goal_id is not None
        ):
            raise ValueError(
                "matched_high_level_goal_id is valid only for "
                "MATCHES_OTHER_HIGH_LEVEL_GOAL."
            )

        requires_hlg_generation = self.decision in {
            "ADD_NEW_HIGH_LEVEL_GOAL",
            "REWRITE_ORIGINAL_HIGH_LEVEL_GOAL",
        }

        if requires_hlg_generation:
            if (
                not self.generation_project_description
                or not self.generation_project_description.strip()
            ):
                raise ValueError(
                    f"{self.decision} requires a non-empty "
                    "generation_project_description."
                )
        elif self.generation_project_description is not None:
            raise ValueError(
                "generation_project_description must be null when the selected "
                "decision does not require HLG generation."
            )

        if not self.rationale.strip():
            raise ValueError("rationale must be a non-empty string.")

        return self


class GlobalGoalEvaluationResult(BaseModel):
    """
    Validated evaluator result for one branch.

    ``generation_request`` is present only when the original top-down HLG
    generator must add a new goal or generate a replacement. The evaluator
    never creates or applies a final ``HighLevelGoal`` object.
    """

    branch_id: str
    decision: GlobalGoalEvaluationDecision
    original_high_level_goal: HighLevelGoal
    reconstructed_high_level_goal: str | None = None
    matched_high_level_goal: HighLevelGoal | None = None
    generation_request: HighLevelGoalGenerationRequest | None = None
    rationale: str
    operational_action: str
    requires_high_level_regeneration: bool
    requires_low_level_regeneration: bool

    @model_validator(mode="after")
    def validate_generation_requirement(self) -> "GlobalGoalEvaluationResult":
        expected_high_level_regeneration = self.decision in {
            "ADD_NEW_HIGH_LEVEL_GOAL",
            "REWRITE_ORIGINAL_HIGH_LEVEL_GOAL",
        }

        if (
            self.requires_high_level_regeneration
            != expected_high_level_regeneration
        ):
            raise ValueError(
                "requires_high_level_regeneration is inconsistent with decision."
            )

        if expected_high_level_regeneration and self.generation_request is None:
            raise ValueError(
                f"{self.decision} requires generation_request."
            )

        if (
            not expected_high_level_regeneration
            and self.generation_request is not None
        ):
            raise ValueError(
                "generation_request must be null when no HLG generation is "
                "required."
            )

        if self.decision == "MATCHES_OTHER_HIGH_LEVEL_GOAL":
            if self.matched_high_level_goal is None:
                raise ValueError(
                    "MATCHES_OTHER_HIGH_LEVEL_GOAL requires "
                    "matched_high_level_goal."
                )
        elif self.matched_high_level_goal is not None:
            raise ValueError(
                "matched_high_level_goal must be null for decisions other than "
                "MATCHES_OTHER_HIGH_LEVEL_GOAL."
            )

        return self


# ---------------------------------------------------------------------------
# Documentation coverage evaluator
# ---------------------------------------------------------------------------


DocumentationCoverageStatus = Literal[
    "COMPLETE",
    "MISSING_HIGH_LEVEL_GOALS",
]


class MissingHighLevelGoalProposal(BaseModel):
    """
    One autonomous documented intention missing from the current HLG set.

    ``project_description`` is a focused description to be used as normal input
    by the top-down HLG generator. It is not the final HLG formulation.
    """

    project_description: str
    actor: Actor
    source_evidence: str
    rationale: str

    @model_validator(mode="after")
    def validate_missing_goal_proposal(self) -> "MissingHighLevelGoalProposal":
        if not self.project_description.strip():
            raise ValueError("project_description must be a non-empty string.")

        if not self.source_evidence.strip():
            raise ValueError("source_evidence must be a non-empty string.")

        if not self.rationale.strip():
            raise ValueError("rationale must be a non-empty string.")

        return self


class DocumentationCoverageLLMOutput(BaseModel):
    """Structured output of the global documentation-coverage evaluator."""

    status: DocumentationCoverageStatus
    missing_high_level_goals: list[MissingHighLevelGoalProposal] = Field(
        default_factory=list
    )
    observations: list[str] = Field(default_factory=list)

    @model_validator(mode="after")
    def validate_status_and_missing_goals(
        self,
    ) -> "DocumentationCoverageLLMOutput":
        if self.status == "COMPLETE" and self.missing_high_level_goals:
            raise ValueError(
                "Status COMPLETE cannot contain missing high-level goals."
            )

        if (
            self.status == "MISSING_HIGH_LEVEL_GOALS"
            and not self.missing_high_level_goals
        ):
            raise ValueError(
                "Status MISSING_HIGH_LEVEL_GOALS requires at least one "
                "missing high-level goal."
            )

        return self


class DocumentationCoverageResult(BaseModel):
    """
    Validated coverage result.

    Missing intentions are converted into generation requests. No final HLG is
    directly generated or added by the documentation-coverage evaluator.
    """

    status: DocumentationCoverageStatus
    missing_high_level_goals: list[MissingHighLevelGoalProposal] = Field(
        default_factory=list
    )
    generation_requests: list[HighLevelGoalGenerationRequest] = Field(
        default_factory=list
    )
    observations: list[str] = Field(default_factory=list)

    @model_validator(mode="after")
    def validate_generation_requests(self) -> "DocumentationCoverageResult":
        if self.status == "COMPLETE" and self.generation_requests:
            raise ValueError(
                "Status COMPLETE cannot contain generation requests."
            )

        if (
            self.status == "MISSING_HIGH_LEVEL_GOALS"
            and not self.generation_requests
        ):
            raise ValueError(
                "Missing documented HLGs require generation requests."
            )

        return self


# ---------------------------------------------------------------------------
# Global refinement-abstraction-verification cycle
# ---------------------------------------------------------------------------


GlobalGoalCycleStopReason = Literal[
    "ALL_BRANCHES_CONFIRMED_AND_DOCUMENTATION_COVERED",
    "MAX_ITERATIONS_REACHED",
    "REPEATED_STATE_DETECTED",
    "BOTTOM_UP_RECONSTRUCTION_FAILED",
    "GLOBAL_EVALUATION_FAILED",
    "DOCUMENTATION_COVERAGE_EVALUATION_FAILED",
    "HIGH_LEVEL_REGENERATION_FAILED",
    "LOW_LEVEL_REGENERATION_FAILED",
]


class GlobalGoalCycleIteration(BaseModel):
    """Complete trace of one outer refinement-abstraction iteration."""

    iteration: int

    input_high_level_goals: HighLevelGoals
    input_low_level_goals: LowLevelGoals

    branch_traceability: dict[str, dict[str, object]] = Field(
        default_factory=dict
    )

    reconstructed_high_level_goals: dict[
        str,
        BottomUpHighLevelGoal,
    ] = Field(default_factory=dict)

    bottom_up_errors: dict[str, str] = Field(default_factory=dict)
    empty_branches: list[str] = Field(default_factory=list)

    global_evaluations: dict[
        str,
        GlobalGoalEvaluationResult,
    ] = Field(default_factory=dict)

    global_evaluation_errors: dict[str, str] = Field(default_factory=dict)

    high_level_generation_requests: list[
        HighLevelGoalGenerationRequest
    ] = Field(default_factory=list)
    generated_high_level_goals: HighLevelGoals | None = None
    high_level_regeneration_error: str | None = None

    documentation_coverage: DocumentationCoverageResult | None = None
    documentation_coverage_error: str | None = None
    documentation_fully_covered: bool = False

    newly_added_high_level_goals: list[HighLevelGoal] = Field(
        default_factory=list
    )

    updated_high_level_goals: HighLevelGoals | None = None
    regenerated_low_level_goals: LowLevelGoals | None = None

    all_branches_confirmed: bool = False
    requires_regeneration: bool = False

    state_signature: str


class GlobalGoalCycleResult(BaseModel):
    converged: bool
    stop_reason: GlobalGoalCycleStopReason
    completed_iterations: int
    max_iterations: int

    final_high_level_goals: HighLevelGoals
    final_low_level_goals: LowLevelGoals

    added_high_level_goals: list[HighLevelGoal] = Field(default_factory=list)
    iterations: list[GlobalGoalCycleIteration] = Field(default_factory=list)

    unresolved_bottom_up_errors: dict[str, str] = Field(default_factory=dict)
    unresolved_global_evaluation_errors: dict[str, str] = Field(
        default_factory=dict
    )
    unresolved_empty_branches: list[str] = Field(default_factory=list)
    unresolved_documentation_coverage_error: str | None = None
    unresolved_high_level_regeneration_error: str | None = None
