"""
Central Pydantic data models for the whole pipeline.

This is the single source of truth for structured data used by both the
original top-down pipeline and the bottom-up feedback-loop extension.
Keeping all schemas here provides one explicit source of truth for model definitions.

The file is organized by pipeline responsibility:
1. shared/top-down core models;
2. bottom-up reconstruction outputs;
3. generation/regeneration requests;
4. duplicate-resolution traces;
5. Global Goal Evaluator outputs;
6. documentation-coverage outputs;
7. outer-cycle traces and results.
"""

from enum import Enum

from pydantic import BaseModel, Field, model_validator


# ---------------------------------------------------------------------------
# Shared / original top-down pipeline models
# ---------------------------------------------------------------------------


class DocumentDescription(BaseModel):
    description: str


class Actor(BaseModel):
    name: str
    description: str


class Actors(BaseModel):
    actors: list[Actor]


class HighLevelGoal(BaseModel):
    name: str
    description: str
    actor: Actor


class HighLevelGoals(BaseModel):
    goals: list[HighLevelGoal]


class LowLevelGoal(BaseModel):
    name: str
    description: str
    high_level_associated: HighLevelGoal


class LowLevelGoals(BaseModel):
    low_level_goals: list[LowLevelGoal]


class API(BaseModel):
    api_name: str
    api_path: str
    description: str
    request_type: str


class APIMapping(BaseModel):
    APIs: list[API]
    low_level_goal: LowLevelGoal


class Critique(BaseModel):
    score: float
    comment: str


# ---------------------------------------------------------------------------
# Bottom-up High-Level Goal reconstruction
# ---------------------------------------------------------------------------


class CohesionLevel(str, Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class ConfidenceLevel(str, Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class BottomUpHighLevelGoalLLMOutput(BaseModel):
    """
    Semantic output requested from the bottom-up High-Level Goal Generator.

    Identifiers and traceability metadata are added deterministically by
    Python and are not generated by the LLM. ``supporting_low_level_goal_ids``
    here holds the branch-LOCAL ids exactly as returned by the LLM (e.g.
    'llg_001'), scoped only to the current prompt.
    """

    reconstructed_high_level_goal: str
    abstraction_rationale: str
    supporting_low_level_goal_ids: list[str] = Field(
        description=(
            "Branch-LOCAL low-level-goal ids selected by the LLM as "
            "evidence for the reconstructed goal (e.g. 'llg_001'), scoped "
            "only to the current prompt. Never full ids."
        )
    )
    cohesion: CohesionLevel
    confidence: ConfidenceLevel


class BottomUpHighLevelGoal(BottomUpHighLevelGoalLLMOutput):
    """
    Final bottom-up reconstruction result for one branch.

    Inherits ``reconstructed_high_level_goal``, ``abstraction_rationale``,
    ``cohesion``, and ``confidence`` unchanged from
    ``BottomUpHighLevelGoalLLMOutput``. ``supporting_low_level_goal_ids`` is
    also inherited by name, but here it holds the FULL ids
    (e.g. 'branch_001_llg_001'): the orchestrator deterministically derives
    them from the LLM's branch-local ids by prefixing each with
    ``branch_id``. The LLM itself never sees or produces full ids.

    The original parent HLG is deliberately excluded. Parent traceability is
    maintained separately by the orchestrator.
    """

    branch_id: str = Field(
        description=(
            "Opaque, deterministic branch identifier ('branch_001', ...) "
            "assigned by Python. Carries no semantic content from the "
            "original parent high-level goal."
        )
    )
    source_low_level_goal_ids: list[str] = Field(
        description=(
            "Full ids ('branch_001_llg_001', ...) of every low-level goal "
            "belonging to this branch, i.e. the complete evidence set given "
            "to the LLM."
        )
    )
    # Deterministically computed in Python as
    # source_low_level_goal_ids - supporting_low_level_goal_ids, preserving
    # the original order of source_low_level_goal_ids. Never produced by the
    # LLM: it is the complement of the ids the bottom-up reconstructor chose
    # as supporting evidence, kept explicit for traceability and experimental
    # analysis. The current Global Goal Evaluator receives only HLG', not the
    # individual LLG evidence lists.
    non_supporting_low_level_goal_ids: list[str] = Field(
        description=(
            "Full ids present in source_low_level_goal_ids but NOT in "
            "supporting_low_level_goal_ids, in source order. Computed "
            "deterministically in Python (never by the LLM) as the "
            "complement of the reconstructor's supporting-evidence "
            "selection; retained for traceability and experimental analysis."
        )
    )


# ---------------------------------------------------------------------------
# Requests for the existing top-down HLG generator
# ---------------------------------------------------------------------------


class HighLevelGoalGenerationAction(str, Enum):
    ADD_NEW_HIGH_LEVEL_GOAL = "ADD_NEW_HIGH_LEVEL_GOAL"
    REPLACE_EXISTING_HIGH_LEVEL_GOAL = "REPLACE_EXISTING_HIGH_LEVEL_GOAL"


class HighLevelGoalGenerationSource(str, Enum):
    BRANCH_EVALUATION = "BRANCH_EVALUATION"
    DOCUMENTATION_COVERAGE = "DOCUMENTATION_COVERAGE"


class HighLevelGoalGeneratorInput(BaseModel):
    """
    Input forwarded to the existing top-down ``generate_high_level_goals``
    function.

    The field names intentionally match the original function parameters:
    ``project_description`` and ``actors``. No information about evaluation,
    correction, replacement, branch identifiers, or previous attempts is
    exposed to the generator.
    """

    project_description: str
    actors: Actors

    @model_validator(mode="after")
    def validate_generator_input(self) -> "HighLevelGoalGeneratorInput":
        if not self.project_description.strip():
            raise ValueError("project_description must be a non-empty string.")

        if not self.actors.actors:
            raise ValueError("actors must contain at least one actor.")

        return self


class HighLevelGoalGenerationRequest(BaseModel):
    """
    One validated request to generate HLGs through the original top-down block.

    ``generator_input`` is the only part forwarded to the HLG generator.
    ``action`` and ``target_branch_id`` are orchestration metadata and are never
    shown to the generator.
    """

    request_id: str
    action: HighLevelGoalGenerationAction
    source: HighLevelGoalGenerationSource
    generator_input: HighLevelGoalGeneratorInput = Field(
        description=(
            "The generation-request payload forwarded to the top-down HLG "
            "generator (project_description + actors)."
        )
    )

    target_branch_id: str | None = Field(
        default=None,
        description=(
            "Branch to replace for REPLACE_EXISTING_HIGH_LEVEL_GOAL; must "
            "be null for ADD_NEW_HIGH_LEVEL_GOAL."
        ),
    )
    origin_branch_id: str | None = Field(
        default=None,
        description=(
            "Branch that produced this request when source is "
            "BRANCH_EVALUATION; required in that case, otherwise unused."
        ),
    )
    generator_guidance: str | None = Field(
        default=None,
        description=(
            "Focused, actionable guidance produced by the bottom-up evaluator "
            "for the original HLG generator. It may explain what intention to "
            "capture or what scope error to correct, but it is not itself a "
            "final High-Level Goal."
        ),
    )
    rationale: str

    @model_validator(mode="after")
    def validate_generation_request(self) -> "HighLevelGoalGenerationRequest":
        if not self.request_id.strip():
            raise ValueError("request_id must be a non-empty string.")

        if not self.rationale.strip():
            raise ValueError("rationale must be a non-empty string.")

        if self.generator_guidance is not None and not self.generator_guidance.strip():
            raise ValueError(
                "generator_guidance must be null or a non-empty string."
            )

        if (
            self.action
            == HighLevelGoalGenerationAction.REPLACE_EXISTING_HIGH_LEVEL_GOAL
        ):
            if not self.target_branch_id:
                raise ValueError(
                    "REPLACE_EXISTING_HIGH_LEVEL_GOAL requires "
                    "target_branch_id."
                )
        elif self.target_branch_id is not None:
            raise ValueError(
                "target_branch_id must be null for ADD_NEW_HIGH_LEVEL_GOAL."
            )

        if (
            self.source == HighLevelGoalGenerationSource.BRANCH_EVALUATION
            and not self.origin_branch_id
        ):
            raise ValueError(
                "A BRANCH_EVALUATION request requires origin_branch_id."
            )

        return self


# ---------------------------------------------------------------------------
# Requests for the original Low-Level Goal generator + evaluator loop
# ---------------------------------------------------------------------------


class LowLevelGoalRegenerationRequest(BaseModel):
    """
    Selective regeneration request used by the bottom-up feedback loop.

    ``high_level_goals`` contains only the HLGs whose decomposition must be
    regenerated. ``guidance_by_parent_name`` carries the Global Goal
    Evaluator's correction/scope suggestions for those HLGs. The callback
    handling this request must run the ORIGINAL LLG generator and its own
    evaluator/reflection loop before returning LowLevelGoals to the bottom-up
    cycle.
    """

    high_level_goals: HighLevelGoals
    guidance_by_parent_name: dict[str, str] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_regeneration_request(
        self,
    ) -> "LowLevelGoalRegenerationRequest":
        if not self.high_level_goals.goals:
            raise ValueError(
                "high_level_goals must contain at least one target HLG."
            )

        target_names = {goal.name for goal in self.high_level_goals.goals}
        unknown_names = set(self.guidance_by_parent_name) - target_names
        if unknown_names:
            raise ValueError(
                "guidance_by_parent_name contains goals that are not present "
                f"in high_level_goals: {sorted(unknown_names)}."
            )

        for parent_name, guidance in self.guidance_by_parent_name.items():
            if not parent_name.strip():
                raise ValueError(
                    "guidance_by_parent_name cannot contain an empty key."
                )
            if not guidance.strip():
                raise ValueError(
                    "guidance_by_parent_name values must be non-empty strings."
                )

        return self


# ---------------------------------------------------------------------------
# Selection among semantically duplicate HLG candidates
# ---------------------------------------------------------------------------


class HighLevelGoalDuplicateCandidateSource(str, Enum):
    """Origin of a candidate shown to the duplicate-selection evaluator."""

    GENERATED = "GENERATED"
    EXISTING = "EXISTING"


class HighLevelGoalRequestSelection(BaseModel):
    """
    Trace of request-level HLG admission before semantic duplicate resolution.

    Every focused request is verified even when the top-down generator returns
    only one candidate. At most one candidate may survive. When the verifier
    rejects all candidates, ``selected_candidate_id`` and ``selected_goal``
    are null and every supplied candidate is recorded in ``discarded_goals``.
    """

    request_id: str
    candidate_ids: list[str]
    selected_candidate_id: str | None = None
    selected_goal: HighLevelGoal | None = None
    discarded_goals: list[HighLevelGoal] = Field(default_factory=list)
    rationale: str

    @model_validator(mode="after")
    def validate_request_candidate_selection(
        self,
    ) -> "HighLevelGoalRequestSelection":
        if not self.request_id.strip():
            raise ValueError("request_id must be a non-empty string.")
        if not self.candidate_ids:
            raise ValueError(
                "A request-level candidate selection requires at least one "
                "candidate id."
            )
        if len(set(self.candidate_ids)) != len(self.candidate_ids):
            raise ValueError("candidate_ids must be unique.")

        if self.selected_candidate_id is None:
            if self.selected_goal is not None:
                raise ValueError(
                    "selected_goal must be null when all candidates are rejected."
                )
            if len(self.discarded_goals) != len(self.candidate_ids):
                raise ValueError(
                    "When all candidates are rejected, discarded_goals must "
                    "contain every supplied candidate."
                )
        else:
            if self.selected_candidate_id not in self.candidate_ids:
                raise ValueError(
                    "selected_candidate_id must belong to candidate_ids."
                )
            if self.selected_goal is None:
                raise ValueError(
                    "selected_goal is required when a candidate is selected."
                )
            if len(self.discarded_goals) != len(self.candidate_ids) - 1:
                raise ValueError(
                    "discarded_goals must contain every non-selected candidate."
                )

        if not self.rationale.strip():
            raise ValueError("rationale must be a non-empty string.")
        return self

    @property
    def rejected_all(self) -> bool:
        """Whether request-level verification deliberately admitted no HLG."""
        return self.selected_candidate_id is None


class HighLevelGoalDuplicateResolution(BaseModel):
    """
    Trace of one evaluator-backed duplicate-resolution decision.

    A duplicate cluster may now contain both HLGs freshly returned by the
    top-down generator and HLGs that already belong to the current cycle
    state.  The evaluator still performs one operation only: choose the
    single candidate that best represents the documented intention and the
    GORE abstraction expected from an HLG.  Python then keeps that winner and
    removes every losing duplicate.

    ``candidate_sources`` records whether each candidate was GENERATED or
    EXISTING.  For existing candidates, ``candidate_branch_ids`` stores the
    current branch id so the update/orchestration layer can deterministically
    remove that branch when an improved generated candidate wins.  Generated
    candidates have a null branch id.
    """

    request_id: str
    candidate_ids: list[str]
    candidate_sources: dict[
        str, HighLevelGoalDuplicateCandidateSource
    ] = Field(default_factory=dict)
    candidate_branch_ids: dict[str, str | None] = Field(default_factory=dict)
    selected_candidate_id: str
    selected_goal: HighLevelGoal
    discarded_goals: list[HighLevelGoal] = Field(default_factory=list)
    rationale: str

    @model_validator(mode="after")
    def validate_duplicate_resolution(
        self,
    ) -> "HighLevelGoalDuplicateResolution":
        if not self.request_id.strip():
            raise ValueError("request_id must be a non-empty string.")
        if len(self.candidate_ids) < 2:
            raise ValueError(
                "A duplicate resolution requires at least two candidate ids."
            )
        if len(set(self.candidate_ids)) != len(self.candidate_ids):
            raise ValueError("candidate_ids must be unique.")
        if self.selected_candidate_id not in self.candidate_ids:
            raise ValueError(
                "selected_candidate_id must belong to candidate_ids."
            )

        candidate_id_set = set(self.candidate_ids)
        if set(self.candidate_sources) != candidate_id_set:
            raise ValueError(
                "candidate_sources must contain exactly one entry for every "
                "candidate_id."
            )
        if set(self.candidate_branch_ids) != candidate_id_set:
            raise ValueError(
                "candidate_branch_ids must contain exactly one entry for "
                "every candidate_id."
            )

        for candidate_id in self.candidate_ids:
            source = self.candidate_sources[candidate_id]
            branch_id = self.candidate_branch_ids[candidate_id]
            if source == HighLevelGoalDuplicateCandidateSource.EXISTING:
                if not branch_id or not branch_id.strip():
                    raise ValueError(
                        "Every EXISTING duplicate candidate requires its "
                        "current branch id."
                    )
            elif branch_id is not None:
                raise ValueError(
                    "A GENERATED duplicate candidate must have a null "
                    "candidate_branch_id."
                )

        if len(self.discarded_goals) != len(self.candidate_ids) - 1:
            raise ValueError(
                "discarded_goals must contain every non-selected candidate."
            )
        if not self.rationale.strip():
            raise ValueError("rationale must be a non-empty string.")
        return self

    @property
    def selected_source(self) -> HighLevelGoalDuplicateCandidateSource:
        """Return the recorded origin of the selected candidate."""
        return self.candidate_sources[self.selected_candidate_id]

    @property
    def selected_existing_branch_id(self) -> str | None:
        """Return the selected branch id when the winner already existed."""
        return self.candidate_branch_ids[self.selected_candidate_id]

    @property
    def discarded_existing_branch_ids(self) -> list[str]:
        """Existing branches that lost against the selected candidate."""
        return [
            branch_id
            for candidate_id, branch_id in self.candidate_branch_ids.items()
            if candidate_id != self.selected_candidate_id
            and self.candidate_sources[candidate_id]
            == HighLevelGoalDuplicateCandidateSource.EXISTING
            and branch_id is not None
        ]


# ---------------------------------------------------------------------------
# Global Goal Evaluator
# ---------------------------------------------------------------------------


class GlobalGoalEvaluationDecision(str, Enum):
    """Two-way decision used by the current branch-level feedback loop."""

    CONFIRM_BRANCH = "CONFIRM_BRANCH"
    REGENERATE_HIGH_LEVEL_GOAL = "REGENERATE_HIGH_LEVEL_GOAL"


class GlobalGoalEvaluationLLMOutput(BaseModel):
    """
    Structured output requested from the current Global Goal Evaluator.

    Branch evaluation is deliberately a single two-way gate. The evaluator
    receives the project documentation, the current HLG collection, the current
    branch id, and the HLG reconstructed bottom-up from that branch's LLGs. It
    does not inspect individual LLGs and does not classify the mismatch as an
    HLG problem versus an LLG problem.

    - ``CONFIRM_BRANCH`` keeps the branch unchanged.
    - ``REGENERATE_HIGH_LEVEL_GOAL`` rebuilds the branch from HLG level; the
      replacement HLG is then always decomposed into newly generated/evaluated
      LLGs before the next bottom-up iteration.
    """

    rationale: str
    decision: GlobalGoalEvaluationDecision = Field(
        description=(
            "The evaluator's local branch decision: CONFIRM_BRANCH or "
            "REGENERATE_HIGH_LEVEL_GOAL."
        )
    )
    matched_branch_id: str | None = Field(
        default=None,
        description=(
            "Legacy compatibility field. It must always be null in the "
            "current two-way branch evaluation."
        ),
    )
    generation_project_description: str | None = Field(
        default=None,
        description=(
            "Focused stakeholder-style project description forwarded to the "
            "original top-down HLG generator only when the decision is "
            "REGENERATE_HIGH_LEVEL_GOAL."
        ),
    )

    @model_validator(mode="after")
    def validate_decision_fields(self) -> "GlobalGoalEvaluationLLMOutput":
        if self.matched_branch_id is not None:
            raise ValueError(
                "matched_branch_id must always be null in the current "
                "two-way branch evaluation."
            )

        requires_hlg_generation = (
            self.decision
            == GlobalGoalEvaluationDecision.REGENERATE_HIGH_LEVEL_GOAL
        )

        if requires_hlg_generation:
            if (
                not self.generation_project_description
                or not self.generation_project_description.strip()
            ):
                raise ValueError(
                    "REGENERATE_HIGH_LEVEL_GOAL requires a non-empty "
                    "generation_project_description."
                )
        elif self.generation_project_description is not None:
            raise ValueError(
                "generation_project_description must be null for "
                "CONFIRM_BRANCH."
            )

        if not self.rationale.strip():
            raise ValueError("rationale must be a non-empty string.")

        return self


# ---------------------------------------------------------------------------
# Legacy evaluator-stage schemas (not used by the current runtime loop)
# ---------------------------------------------------------------------------


class BranchConsistencyLLMOutput(BaseModel):
    """
    Stage 1 output: does the current low-level decomposition reconstruct its
    own parent high-level goal correctly?

    Answers only the parent/candidate/decomposition-consistency question. It
    must never compare the candidate with other high-level goals and must
    never decide MATCHES_OTHER_HIGH_LEVEL_GOAL, ADD_NEW_HIGH_LEVEL_GOAL, or
    REWRITE_ORIGINAL_HIGH_LEVEL_GOAL.
    """

    rationale: str
    parent_supported: bool
    candidate_supported: bool
    preserves_parent_intention: bool
    decomposition_complete: bool

    @model_validator(mode="after")
    def validate_rationale(self) -> "BranchConsistencyLLMOutput":
        if not self.rationale.strip():
            raise ValueError("rationale must be a non-empty string.")
        return self

    @property
    def confirms_branch(self) -> bool:
        return (
            self.parent_supported
            and self.candidate_supported
            and self.preserves_parent_intention
            and self.decomposition_complete
        )


class OtherGoalMatchLLMOutput(BaseModel):
    """
    Stage 2 output: does the candidate correspond to another already-extracted
    high-level goal of the project?

    Only evaluated when Stage 1 did not confirm the branch. Must never decide
    whether to add or rewrite a high-level goal.

    ``matched_branch_id`` (not ``matched_high_level_goal_id``) on purpose: the
    value the model must return is the opaque branch identifier shown to it
    (e.g. ``branch_005``), never the HLG's own name/label, which is a
    different string the model could otherwise confuse it with.
    """

    rationale: str
    matches_other_high_level_goal: bool
    matched_branch_id: str | None = None

    @model_validator(mode="after")
    def validate_match_fields(self) -> "OtherGoalMatchLLMOutput":
        if not self.rationale.strip():
            raise ValueError("rationale must be a non-empty string.")

        if self.matches_other_high_level_goal:
            if not self.matched_branch_id:
                raise ValueError(
                    "matches_other_high_level_goal=True requires a non-null "
                    "matched_branch_id."
                )
        elif self.matched_branch_id is not None:
            raise ValueError(
                "matched_branch_id must be null when "
                "matches_other_high_level_goal is False."
            )

        return self


class GoalDiscoveryOutcome(str, Enum):
    REGENERATE_LOW_LEVEL_GOALS = "REGENERATE_LOW_LEVEL_GOALS"
    ADD_NEW_HIGH_LEVEL_GOAL = "ADD_NEW_HIGH_LEVEL_GOAL"
    REWRITE_ORIGINAL_HIGH_LEVEL_GOAL = "REWRITE_ORIGINAL_HIGH_LEVEL_GOAL"


class GoalDiscoveryLLMOutput(BaseModel):
    """
    Stage 3 output: given that the candidate does not correctly reconstruct
    its own parent and does not correspond to another already-extracted
    high-level goal, what does the evidence indicate?

    Only evaluated when Stage 1 did not confirm the branch and Stage 2 found
    no match with another high-level goal.
    """

    rationale: str
    outcome: GoalDiscoveryOutcome
    generation_project_description: str | None = Field(
        default=None,
        description=(
            "Ordinary stakeholder-style project description forwarded "
            "as-is to the top-down HLG generator; non-null only for "
            "ADD_NEW_HIGH_LEVEL_GOAL / REWRITE_ORIGINAL_HIGH_LEVEL_GOAL."
        ),
    )

    @model_validator(mode="after")
    def validate_outcome_fields(self) -> "GoalDiscoveryLLMOutput":
        if not self.rationale.strip():
            raise ValueError("rationale must be a non-empty string.")

        requires_hlg_generation = self.outcome in {
            GoalDiscoveryOutcome.ADD_NEW_HIGH_LEVEL_GOAL,
            GoalDiscoveryOutcome.REWRITE_ORIGINAL_HIGH_LEVEL_GOAL,
        }

        if requires_hlg_generation:
            if (
                not self.generation_project_description
                or not self.generation_project_description.strip()
            ):
                raise ValueError(
                    f"{self.outcome} requires a non-empty "
                    "generation_project_description."
                )
        elif self.generation_project_description is not None:
            raise ValueError(
                "generation_project_description must be null for "
                "REGENERATE_LOW_LEVEL_GOALS."
            )

        return self


class GlobalGoalEvaluationResult(BaseModel):
    """
    Validated result of the current two-way branch evaluator.

    A non-empty branch has only two possible states:
    - ``CONFIRM_BRANCH``: keep the current HLG and its current LLGs;
    - ``REGENERATE_HIGH_LEVEL_GOAL``: generate one replacement HLG through the
      original HLG Generator -> HLG Evaluator loop and then always generate a
      fresh LLG decomposition for that replacement through the original LLG
      Generator -> LLG Evaluator loop.

    ``matched_high_level_goal`` is retained as a legacy-compatible field but is
    always null in the current runtime policy.
    """

    branch_id: str
    decision: GlobalGoalEvaluationDecision
    original_high_level_goal: HighLevelGoal
    reconstructed_high_level_goal: str | None = None
    matched_high_level_goal: HighLevelGoal | None = None
    generation_request: HighLevelGoalGenerationRequest | None = None
    rationale: str
    operational_action: str = Field(
        description=(
            "Human-readable operational label mirroring the current two-way "
            "decision, used only for logging and traceability."
        )
    )
    requires_high_level_regeneration: bool
    requires_low_level_regeneration: bool

    @model_validator(mode="after")
    def validate_generation_requirement(self) -> "GlobalGoalEvaluationResult":
        requires_branch_regeneration = (
            self.decision
            == GlobalGoalEvaluationDecision.REGENERATE_HIGH_LEVEL_GOAL
        )

        if (
            self.requires_high_level_regeneration
            != requires_branch_regeneration
        ):
            raise ValueError(
                "requires_high_level_regeneration is inconsistent with "
                "the branch decision."
            )

        # Under the current policy a regenerated HLG must always receive a
        # completely new LLG decomposition before the next iteration.
        if self.requires_low_level_regeneration != requires_branch_regeneration:
            raise ValueError(
                "requires_low_level_regeneration is inconsistent with the "
                "current whole-branch regeneration policy."
            )

        if requires_branch_regeneration and self.generation_request is None:
            raise ValueError(
                "REGENERATE_HIGH_LEVEL_GOAL requires generation_request."
            )

        if not requires_branch_regeneration and self.generation_request is not None:
            raise ValueError(
                "generation_request must be null for CONFIRM_BRANCH."
            )

        if self.matched_high_level_goal is not None:
            raise ValueError(
                "matched_high_level_goal must always be null in the current "
                "two-way branch evaluation."
            )

        if not self.rationale.strip():
            raise ValueError("rationale must be a non-empty string.")

        return self


# ---------------------------------------------------------------------------
# Documentation coverage evaluator
# ---------------------------------------------------------------------------


class DocumentationCoverageStatus(str, Enum):
    COMPLETE = "COMPLETE"
    MISSING_HIGH_LEVEL_GOALS = "MISSING_HIGH_LEVEL_GOALS"


class MissingHighLevelGoalProposal(BaseModel):
    """
    One autonomous documented intention missing from the current HLG set.

    ``project_description`` is a focused description to be used as normal input
    by the top-down HLG generator. It is not the final HLG formulation.
    """

    project_description: str
    actor: Actor
    source_evidence: str
    rationale: str

    @model_validator(mode="after")
    def validate_missing_goal_proposal(self) -> "MissingHighLevelGoalProposal":
        if not self.project_description.strip():
            raise ValueError("project_description must be a non-empty string.")

        if not self.source_evidence.strip():
            raise ValueError("source_evidence must be a non-empty string.")

        if not self.rationale.strip():
            raise ValueError("rationale must be a non-empty string.")

        return self


class DocumentationCoverageSelectionLLMOutput(BaseModel):
    """
    Second-stage verifier output for documentation-coverage proposals.

    The coverage detector is recall-oriented: it may propose several plausible
    missing intentions. This verifier selects the minimal non-redundant subset
    that is both documentation-grounded and genuinely at HLG abstraction
    level. An empty list is valid at this stage and causes the detector to be
    retried rather than silently adding a speculative goal.
    """

    selected_proposal_ids: list[str] = Field(default_factory=list)
    rationale: str

    @model_validator(mode="after")
    def validate_coverage_selection(
        self,
    ) -> "DocumentationCoverageSelectionLLMOutput":
        if len(set(self.selected_proposal_ids)) != len(
            self.selected_proposal_ids
        ):
            raise ValueError("selected_proposal_ids must be unique.")
        if any(
            not proposal_id.strip()
            for proposal_id in self.selected_proposal_ids
        ):
            raise ValueError(
                "selected_proposal_ids cannot contain empty identifiers."
            )
        if not self.rationale.strip():
            raise ValueError("rationale must be a non-empty string.")
        return self


class DocumentationCoverageLLMOutput(BaseModel):
    """Structured output of the global documentation-coverage evaluator."""

    status: DocumentationCoverageStatus
    missing_high_level_goals: list[MissingHighLevelGoalProposal] = Field(
        default_factory=list
    )
    observations: list[str] = Field(default_factory=list)

    @model_validator(mode="after")
    def validate_status_and_missing_goals(
        self,
    ) -> "DocumentationCoverageLLMOutput":
        if (
            self.status == DocumentationCoverageStatus.COMPLETE
            and self.missing_high_level_goals
        ):
            raise ValueError(
                "Status COMPLETE cannot contain missing high-level goals."
            )

        if (
            self.status == DocumentationCoverageStatus.MISSING_HIGH_LEVEL_GOALS
            and not self.missing_high_level_goals
        ):
            raise ValueError(
                "Status MISSING_HIGH_LEVEL_GOALS requires at least one "
                "missing high-level goal."
            )

        return self


class DocumentationCoverageResult(BaseModel):
    """
    Validated coverage result.

    Missing intentions are converted into generation requests. No final HLG is
    directly generated or added by the documentation-coverage evaluator.
    """

    status: DocumentationCoverageStatus
    missing_high_level_goals: list[MissingHighLevelGoalProposal] = Field(
        default_factory=list
    )
    generation_requests: list[HighLevelGoalGenerationRequest] = Field(
        default_factory=list
    )
    observations: list[str] = Field(default_factory=list)

    @model_validator(mode="after")
    def validate_generation_requests(self) -> "DocumentationCoverageResult":
        if (
            self.status == DocumentationCoverageStatus.COMPLETE
            and self.generation_requests
        ):
            raise ValueError(
                "Status COMPLETE cannot contain generation requests."
            )

        if (
            self.status == DocumentationCoverageStatus.MISSING_HIGH_LEVEL_GOALS
            and not self.generation_requests
        ):
            raise ValueError(
                "Missing documented HLGs require generation requests."
            )

        return self


# ---------------------------------------------------------------------------
# Global refinement-abstraction-verification cycle
# ---------------------------------------------------------------------------


class GlobalGoalCycleStopReason(str, Enum):
    ALL_BRANCHES_CONFIRMED_AND_DOCUMENTATION_COVERED = (
        "ALL_BRANCHES_CONFIRMED_AND_DOCUMENTATION_COVERED"
    )
    MAX_ITERATIONS_REACHED = "MAX_ITERATIONS_REACHED"
    REPEATED_STATE_DETECTED = "REPEATED_STATE_DETECTED"
    SEMANTIC_REPEATED_STATE_DETECTED = "SEMANTIC_REPEATED_STATE_DETECTED"
    BOTTOM_UP_RECONSTRUCTION_FAILED = "BOTTOM_UP_RECONSTRUCTION_FAILED"
    GLOBAL_EVALUATION_FAILED = "GLOBAL_EVALUATION_FAILED"
    DOCUMENTATION_COVERAGE_EVALUATION_FAILED = (
        "DOCUMENTATION_COVERAGE_EVALUATION_FAILED"
    )
    HIGH_LEVEL_REGENERATION_FAILED = "HIGH_LEVEL_REGENERATION_FAILED"
    LOW_LEVEL_REGENERATION_FAILED = "LOW_LEVEL_REGENERATION_FAILED"


class GlobalGoalCycleIteration(BaseModel):
    """Complete trace of one outer refinement-abstraction iteration."""

    iteration: int

    input_high_level_goals: HighLevelGoals
    input_low_level_goals: LowLevelGoals

    branch_traceability: dict[str, dict[str, object]] = Field(
        default_factory=dict
    )

    reconstructed_high_level_goals: dict[
        str,
        BottomUpHighLevelGoal,
    ] = Field(default_factory=dict)

    bottom_up_errors: dict[str, str] = Field(default_factory=dict)
    empty_branches: list[str] = Field(default_factory=list)

    global_evaluations: dict[
        str,
        GlobalGoalEvaluationResult,
    ] = Field(default_factory=dict)

    global_evaluation_errors: dict[str, str] = Field(default_factory=dict)

    high_level_generation_requests: list[
        HighLevelGoalGenerationRequest
    ] = Field(default_factory=list)
    generated_high_level_goals: HighLevelGoals | None = None
    high_level_request_candidate_selections: list[
        HighLevelGoalRequestSelection
    ] = Field(
        default_factory=list,
        description=(
            "Selections that enforce exactly one surviving GENERATED HLG "
            "for each focused generation request before semantic duplicate "
            "resolution against other generated or existing goals."
        ),
    )
    high_level_duplicate_resolutions: list[
        HighLevelGoalDuplicateResolution
    ] = Field(default_factory=list)
    high_level_regeneration_error: str | None = None

    documentation_coverage: DocumentationCoverageResult | None = None
    documentation_coverage_rechecks: list[
        DocumentationCoverageResult
    ] = Field(
        default_factory=list,
        description=(
            "Explicit documentation-coverage evaluations performed again "
            "inside the same outer iteration after a generated HLG was "
            "discarded because an existing semantic duplicate was selected "
            "as the better representative. The cycle converges only if one "
            "of these re-checks explicitly returns COMPLETE."
        ),
    )
    documentation_coverage_error: str | None = None
    documentation_fully_covered: bool = False

    newly_added_high_level_goals: list[HighLevelGoal] = Field(
        default_factory=list
    )

    updated_high_level_goals: HighLevelGoals | None = None
    regenerated_low_level_goals: LowLevelGoals | None = None

    all_branches_confirmed: bool = False
    requires_regeneration: bool = False

    state_signature: str = Field(
        description=(
            "SHA-256 canonical-JSON digest of this iteration's structural "
            "state (HLGs + LLGs + structural branch decisions, free text "
            "excluded), used for exact repeated-state detection."
        )
    )


class GlobalGoalCycleResult(BaseModel):
    """
    Final trace/result of the single evolving HLG/LLG state.

    The cycle never ranks previous iterations and never rolls back to a
    previously observed goal set. ``final_*`` always contains the current
    HLG/LLG collection reached when execution stops. It is a validated final
    model only when ``converged`` is True; otherwise it is the latest snapshot
    retained for diagnostics and experimental traceability.

    ``best_validated_*`` remains in the schema only for compatibility with
    existing consumers and is always set to ``None`` by the current
    ``cycle_state._build_result`` implementation. ``last_candidate_*`` mirrors
    the current collection.
    """

    converged: bool
    stop_reason: GlobalGoalCycleStopReason
    completed_iterations: int
    max_iterations: int

    final_high_level_goals: HighLevelGoals
    final_low_level_goals: LowLevelGoals

    best_validated_high_level_goals: HighLevelGoals | None = Field(
        default=None,
        description=(
            "Legacy compatibility field. The current cycle has no best-state "
            "selection policy and sets this field to None."
        ),
    )
    best_validated_low_level_goals: LowLevelGoals | None = Field(
        default=None,
        description=(
            "Legacy compatibility field. The current cycle has no best-state "
            "selection policy and sets this field to None."
        ),
    )

    last_candidate_high_level_goals: HighLevelGoals = Field(
        description=(
            "The current HLG collection reached when execution stops; it "
            "mirrors final_high_level_goals in the current single-state policy."
        )
    )
    last_candidate_low_level_goals: LowLevelGoals = Field(
        description=(
            "The current LLG collection reached when execution stops; it "
            "mirrors final_low_level_goals in the current single-state policy."
        )
    )

    added_high_level_goals: list[HighLevelGoal] = Field(default_factory=list)
    iterations: list[GlobalGoalCycleIteration] = Field(default_factory=list)

    unresolved_bottom_up_errors: dict[str, str] = Field(default_factory=dict)
    unresolved_global_evaluation_errors: dict[str, str] = Field(
        default_factory=dict
    )
    unresolved_empty_branches: list[str] = Field(default_factory=list)
    unresolved_documentation_coverage_error: str | None = None
    unresolved_high_level_regeneration_error: str | None = None